import "../styles/global.style";

import type { AppProps } from "next/app";
import Head from "next/head";
import "./main.css"

function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Color Department — Los Angeles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default App;
