import Head from "next/head";
import type { NextPage } from "next";
import React from "react";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Шаблон</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Шаблон проекта на Next.js!</h1>
      </main>
    </div>
  );
};

export default Home;
