import Head from "next/head";
import type {NextPage} from "next";
import React, {useRef, useState} from "react";
import {useNoScroll} from "../utils/common";

const Home: NextPage = () => {
    const dialogRef = useRef<HTMLDivElement>(null);
    const [isOpenModal, setOpenModal] = useState(false);
    useNoScroll(isOpenModal);

    return (
        <div>
            <Head>
                <title>Шаблон</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <h1>Шаблон проекта на Next.js!</h1>
                <button id='show' onClick={() => {
                    setOpenModal(true)
                    dialogRef.current?.classList.add('show')
                }}>Show Dialog
                </button>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='text'>
                    <p>It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of
                        foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of
                        Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair,
                        we had everything before us, we had nothing before us, we were all going direct to Heaven, we
                        were all going direct the other way-- in short, the period was so far like the present period,
                        that some of its noisiest authorities insisted on its being received, for good or for evil, in
                        the superlative degree of comparison only.</p>

                    <p>There were a king with a large jaw and a queen with a plain face, on the throne of England; there
                        were a king with a large jaw and a queen with a fair face, on the throne of France. In both
                        countries it was clearer than crystal to the lords of the State preserves of loaves and fishes,
                        that things in general were settled for ever.</p>

                    <p>It was the year of Our Lord one thousand seven hundred and seventy-five. Spiritual revelations
                        were conceded to England at that favoured period, as at this. Mrs. Southcott had recently
                        attained her five-and-twentieth blessed birthday, of whom a prophetic private in the Life Guards
                        had heralded the sublime appearance by announcing that arrangements were made for the swallowing
                        up of London and Westminster. Even the Cock-lane ghost had been laid only a round dozen of
                        years, after rapping out its messages, as the spirits of this very year last past
                        (supernaturally deficient in originality) rapped out theirs. Mere messages in the earthly order
                        of events had lately come to the English Crown and People, from a congress of British subjects
                        in America: which, strange to relate, have proved more important to the human race than any
                        communications yet received through any of the chickens of the Cock-lane brood.</p>
                </div>
                <div id='dialog' ref={dialogRef}>
                    <span>Whatever it is</span>
                    <button id='close' onClick={() => {
                        setOpenModal(false)
                        dialogRef.current?.classList.remove('show')
                    }}>Close Dialog
                    </button>
                </div>
            </main>
        </div>
    );
};

export default Home;
